### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by niqixash** [hasandramali/xash3d-schl#3]
/opt/xash3d-schl/dlls/nodes.cpp: In member function 'void CGraph::InitGraph()':
/opt/xash3d-schl/dlls/nodes.cpp:113:68: error: too many arguments to function
  SERVER_COMMAND( "exec maps/%s.cfg\n", STRING( gpGlobals->mapname ));
                                                                    ^
make[2]: *** [dlls/CMakeFiles/server.dir/build.make:934: dlls/CMakeFiles/server.dir/nodes.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: dlls/CMakeFiles/server.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by stephen-cusi** [comment]
作者不会解决它？

**Comment by stephen-cusi** [comment]
I doubt the author will fix it

**Comment by niqixash** [comment]
> duvido que o autor resolva

I fixed this bug in my fork, but I won't fix all remaining bugs

https://github.com/pitFz/xash3d-schl
